### ISSUE TITLE
Проблема при запуске майнера ImportError: DLL load failed while importing _cl: Не найден указанный модуль

### ISSUE THREAD

**Issue by MaikerS55** [EvgeniyKorepov/Watchdog4DanilaMiner#14]
Система windows 10 x64, rtx3060 rev1, дрова 497.29 (пробовал ещё с версией 470.05) пробовал старую версию майнера и новую, результат одинаковый.

> Traceback (most recent call last):
>   File "run.py", line 11, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "task_pool.py", line 3, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "solvers\__init__.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "solvers\opencl\__init__.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "solvers\opencl\opencl.py", line 2, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "solvers\opencl\bus_id.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "pyopencl\__init__.py", line 28, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "pyopencl\cltypes.py", line 22, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "pyopencl\tools.py", line 36, in <module>
> ImportError: DLL load failed while importing _cl: Не найден указанный модуль.
> [2896] Failed to execute script 'run' due to unhandled exception

**Comment by MaikerS55** [comment]
Проблема решена установкой пакета Microsoft Visual C++ 2015
Странно, что нет проверки и подгрузки этого пакета автоматически.
