### ISSUE TITLE
Ошибка при запуске Danila miner

### ISSUE THREAD

**Issue by sharonof** [EvgeniyKorepov/Watchdog4DanilaMiner#22]
Добрый день.
В чем может быть проблема при запуске. программы появляется ошибка
Операционная система WINDOWS 10. Драйвер NVIDIA 472.84      
Вот такую ошибку при запуске выдает 2022.01.06 09:40:47 Application ready
2022.01.06 09:40:52 Use miner version 2.3.1
2022.01.06 09:40:53 START
2022.01.06 09:40:55 Traceback (most recent call last):
2022.01.06 09:40:55 File "run.py", line 11, in <module>
2022.01.06 09:40:55 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:55 File "task_pool.py", line 3, in <module>
2022.01.06 09:40:55 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:55 File "solvers\__init__.py", line 1, in <module>
2022.01.06 09:40:55 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:55 File "solvers\opencl\__init__.py", line 1, in <module>
2022.01.06 09:40:55 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:55 File "solvers\opencl\opencl.py", line 2, in <module>
2022.01.06 09:40:55 File "pyopencl\cltypes.py", line 22, in <module>
2022.01.06 09:40:55 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:55 File "pyopencl\tools.py", line 36, in <module>
2022.01.06 09:40:55 ImportError: DLL load failed while importing _cl: =х эрщфхэ єърчрээvщ ьюфєы№.
2022.01.06 09:40:55 [
2022.01.06 09:40:55 7
2022.01.06 09:40:55 ] Failed to execute script 'run' due to unhandled exception!
2022.01.06 09:40:56 Restart reason : "error" in output
2022.01.06 09:40:56 STOP
2022.01.06 09:40:57 START
2022.01.06 09:40:58 Traceback (most recent call last):
2022.01.06 09:40:58 File "run.py", line 11, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "task_pool.py", line 3, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "solvers\__init__.py", line 1, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "solvers\opencl\__init__.py", line 1, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "solvers\opencl\opencl.py", line 2, in <module>
2022.01.06 09:40:58 File "solvers\opencl\bus_id.py", line 1, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "pyopencl\__init__.py", line 28, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "pyopencl\cltypes.py", line 22, in <module>
2022.01.06 09:40:58 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:40:58 File "pyopencl\tools.py", line 36, in <module>
2022.01.06 09:40:58 ImportError: DLL load failed while importing _cl: =х эрщфхэ єърчрээvщ ьюфєы№.
2022.01.06 09:40:58 [
2022.01.06 09:40:58 4
2022.01.06 09:40:58 Failed to execute script 'run' due to unhandled exception!
2022.01.06 09:40:59 Restart reason : "error" in output
2022.01.06 09:40:59 STOP
2022.01.06 09:41:01 START
2022.01.06 09:41:02 Traceback (most recent call last):
2022.01.06 09:41:02 File "run.py", line 11, in <module>
2022.01.06 09:41:02 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:41:02 File "task_pool.py", line 3, in <module>
2022.01.06 09:41:02 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:41:02 File "solvers\__init__.py", line 1, in <module>
2022.01.06 09:41:02 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:41:02 File "solvers\opencl\__init__.py", line 1, in <module>
2022.01.06 09:41:02 File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
2022.01.06 09:41:02 File "solvers\opencl\opencl.py", line 2, in <module>
2022.01.06 09:41:02 File "PyInstaller\loader\pyimod03_importers.py",

**Comment by sharonof** [comment]
Проблема решена необходимо было скачать Microsoft Visual C++ 2015
